### ISSUE TITLE
disable commands.yml

### ISSUE THREAD

**Issue by xion87** [AuthMe/AuthMeReloaded#1094]
Is possible to disable commands.yml? i dont want any command, and if i delete the code it keep to regenerating....

**Comment by ljacqu** [comment]
You're right, same for the email files. 

### Task
- Add option in config to toggle forced commands
- if disabled, do not load/generate commands.yml or email files

**Comment by Twonox** [comment]
Good idea.

**Comment by ljacqu** [comment]
Inclined to close this as a wontfix:
- default commands.yml no longer executes any command. Version 5.2 shipped with a default that did that... I believe the origin of this issue was this.
- it's difficult for us to check whether emails are enabled or not where we read the email files. In a way I'm also not particularly against having all config files, should the user change settings he won't need to actually run AuthMe to magically get new config files. I understand that this is an easy excuse not to implement that but we'd really have to restructure the settings code... :)

Is this OK for you to close @xion87?

**Comment by xion87** [comment]
is ok i just fixed by myself by editing the file

**Comment by ljacqu** [comment]
Thanks for the feedback, and sorry for the delay.
