### ISSUE TITLE
Add UnregisterEvent to api

### ISSUE THREAD

**Issue by TerZer** [AuthMe/AuthMeReloaded#1169]
Can you add event like UnregisterEvent in API? WOULD BE GREAT!

**Comment by ljacqu** [comment]
Turned out a bit complicated because we have different ways how a player can be unregistered (he may wish to do so, or it may come from a third party: from an admin using `/authme unregister` or from use of our API).

In any case, an `AbstractUnregisterEvent` is fired, which may be either an `UnregisterByPlayerEvent` or an `UnregisterByAdminEvent`. They have different contracts in terms of which data they have and which values they guarantee to _always_ have.

Please verify if this corresponds to your expectation and close this issue or let us know what's missing.

**Comment by TerZer** [comment]
@ljacqu wanted to check everything but... https://github.com/AuthMe/AuthMeReloaded/issues/1192

**Comment by sgdc3** [comment]
@TerZer could you test it again please? ;)

**Comment by TerZer** [comment]
@sgdc3 I just changed to `UnregisterByPlayerEvent` and `UnregisterByAdminEvent`. They worked perfectly on release. If you made changes I can test. :)

**Comment by ljacqu** [comment]
That was all, so thanks for the feedback! :) We can now close this
