### ISSUE TITLE
Translations: recovery_change_password

### ISSUE THREAD

**Issue by jeremy100** [AuthMe/AuthMeReloaded#1178]
Hello, in the translations "recovery_change_password" the command "/ email setpassword [newPassword]" -> setpassword <- does it refer to the current password or to the code generated by the Email in order to change the password?

A greeting!

**Comment by ljacqu** [comment]
Hi @jeremy100, sorry for the late reply. This is literally the command that the user must perform: once he enters the correct code as /email code [code] he is prompted to enter his new password by doing /email setpassword [newPassword].

Full example:
Player does /email recovery hismail@example.com
-> Email is sent saying player should do /email code 1a4f329
Player runs command /email code 1a4f329
-> Player is told to use /email setpassword &lt;newPassword>
Player runs command /email setpassword testeroni
-> Password is updated
Player can log in with /login testeroni

^ The above happens when `Security.recoveryCode` settings don't disable the recovery code. If the recovery code is disabled, /email recovery &lt;mail> will set the player's password immediately to a random new one and the password is mailed to the player.

**Comment by jeremy100** [comment]
Thank you for clarifying my doubts.

Regards!
