### ISSUE TITLE
AllowedRestrictedUser Wildcard

### ISSUE THREAD

**Issue by Faicu** [AuthMe/AuthMeReloaded#1227]
Hello! I want to use AllowedRestrictedUser to restrict my username, Faicu to my IP. But, I have dynamic IP and it is modifying daily with a NEW part of it. Example: 23.33.55.10 today. 23.33.55.11, tomorrow and I want, if possible to use wildcard at last series of numbers, like: 23.33.55.* or 23.33.55.% something like this.

### Environment description
BungeeCord - Spigot

### AuthMe build number:
5.2 1542

**Comment by rautamiekka** [comment]
The added RegEx support is a great addition, but AFAIS no documentation changes were done which clearly state you have to use Java-specific RegEx syntax.

**Comment by ljacqu** [comment]
The best way would be if we supported `*` as wildcard. Would not require any regex prefix and is probably what the user would expect. I'm not sure how it could be best implemented, though :/

**Comment by rautamiekka** [comment]
^ I think that should internally be done as a RegEx regardless since it provides a massive range of possibilities. In which case you could do this (designed for Perl but should work with Java when Java's additional requirements are met):

- Escape characters as needed, except the `*` if we'll use it as the wildcard.
- If it's an IPv4 address, replace `*` with `[0-9]{1,3}` (I know, this allows IPv4 `0.0.0.0`-`999.999.999.999`, but that's not really any of our concern). If it's a string (username, etc.), with `.*`.
- Run the string through RegEx matcher like usual.
- Do your stuff.

**Comment by ljacqu** [comment]
I've tested the new regex feature successfully on an online server, so in the interest of keeping our tracking clean (milestones and whatnot) I open a follow-up issue and close this.
