### ISSUE TITLE
Thread starvation or clock leap detected

### ISSUE THREAD

**Issue by l89669** [AuthMe/AuthMeReloaded#1266]
[08:53:52] [AuthMeMYSQLPool housekeeper/WARN] [/]: [AuthMeMYSQLPool housekeeper] WARN fr.xephi.authme.libs.zaxxer.hikari.pool.HikariPool - AuthMeMYSQLPool - Thread starvation or clock leap detected (housekeeper delta=50s535ms68µs832ns).

this message keep spamming for 1 hour and then my CPU load is 100%, memory load is 100%, the whole server stopped responding, and I have to kill the process and make a restart

AuthMe 5.3.1 release (legacy)
Thermos 58 forge 1614 Minecraft 1.7.10 (SpecialSource is updated) with 6Gb memory allocated
Java is Java 8u121
MySQL is mariadb-server-5.5.52-1.el7.x86_64
CentOS 7.2 (16Gb Memory, Xeon E5 x2) on Aliyun Cloud Service

**Comment by sgdc3** [comment]
Probably it's an issue with thermos, should be fine on spigot.

**Comment by games647** [comment]
Do you run a ntp daemon?

**Comment by l89669** [comment]
The problem happens after I upgrade from 5.2.

**Comment by l89669** [comment]
Don't know what is ntp...

**Comment by l89669** [comment]
I'm going to write a plugin to timely trigger gc command to track tps and memory information from console log. I want to find out which happens first,  the memory leak, tps go down or the authme spam.

**Comment by games647** [comment]
>Don't know what is ntp...

Network time protocol. It synchronized the time. The message you get means that the operation system clock jumped forward. This could happen:

- the CPU was going to sleep (i.e. power saving mode or laptop sleep). 
- bug in the virtualization software of the host operation system. Since this a cloud instance and could be fixed by running an ntp daemon on your server too in order to make manually synchronization with a ntp server
- high CPU load that the house keeper thread of hikari couldn't run.

**Comment by l89669** [comment]
Run System.gc() timely do make this issue disappear, I think there may be memory leak in other code, not authme's fault.
