### ISSUE TITLE
Force only users with a permission to register

### ISSUE THREAD

**Issue by Remski01** [AuthMe/AuthMeReloaded#1387]
How can i set that only a few ranks need to have a registered thing?

As example: Ranks lower the Admin dont register. Nor have they the option. Admins and higher are required to register and login everytime.

Note:
Sorry if this is on the wrong place. I am very noob because i dont understand how the "Pull Request" section works.

**Comment by ljacqu** [comment]
Not a bug, but a feature request :) So far this is not possible with AuthMe. We could probably introduce a permission that would require registration.

**Comment by DutchUser** [comment]
Can you add it?

I just want this for my Mods and higher,

**Comment by ljacqu** [comment]
Yep, this issue now stands for doing it.

**Comment by StrafeZ** [comment]
Any updates on this?

**Comment by ljacqu** [comment]
Although it has been requested by a few people, this is quite low in my personal priorities because it doesn't really offer much. If you want to force staff to register you can remove their /unregister permission.

**Comment by DutchUser** [comment]
"If you want to force staff to register you can remove their /unregister permission." 

I dont understand how this fixed the issue not having this option. Because now everyone is forced to create a password. Staff member or not. 

That's why we requested that the plugin checks based on permission and not just on the UUID to check it have a password.

No offens though. Its a great plugin. Great for the security of the server and the player's.

**Comment by ljacqu** [comment]
> No offens though. Its a great plugin.

None taken! Opinions and requests are very welcome. I don't know how you use AuthMe or how you want to use it, so it's always helpful to get feedback. I really appreciate you taking the time to hash this out.

I'm under the impression that if registration is set to optional (`settings.registration.force: false`) and the permission to /unregister is taken away from staff, it should enable what you are looking for.
The reason this isn't high on my list is that this always gets requested for _staff_, and IMHO the situation with staff should be that they _know_ they need to keep their account registered. Otherwise, in my eyes, it's more of a communication issue or a bad choice in staff than AuthMe missing this feature.

**Comment by DutchUser** [comment]
How is this a bad choice in staff? I looked for this because i want to let the staff teams account be secured so that IF one get hacked or used by someone else that abuse the powers of the staff members.

And i can work with the "I'm under the impression that if registration is set to optional (settings.registration.force: false) and the permission to /unregister is taken away from staff, it should enable what you are looking for." option. (I just going add it as a requirement)

But i sill thinks that make a option to let the plugin first check if a player have a "non-force" permission is a good thing for the plugin to have. Atleast have it as a "ToDo" thing.

Because while this can work for some folks, A lot otehr may still can not work with it.

**Comment by StrafeZ** [comment]
any updates?

**Comment by ljacqu** [comment]
For me personally this is very low on the prio list because of the reasons mentioned in this thread. We'll probably have to already have to kick out stuff we planned for 5.5 so for now I undo the milestone.

**Comment by ARandomAssGuy** [comment]
> For me personally this is very low on the prio list because of the reasons mentioned in this thread. We'll probably have to already have to kick out stuff we planned for 5.5 so for now I undo the milestone.

im assuming its never going to be added?

**Comment by Remski01** [comment]
Because there doesnt seem to be any interest from the devs and because its now 3 years old i decided to remove this from our ticket systeem and close this ticket.
