### ISSUE TITLE
Error Hash PHPBB 3.1.10

### ISSUE THREAD

**Issue by drAkeTool** [AuthMe/AuthMeReloaded#1400]
hello, I have a problem with the hash password
I currently have a PHPBB forum, but I can not make the hash work
It correctly detects the user, but when it enters the password, it says the password is wrong.

I'm using:
Spit 1.12.1
Authme 5.3.2
PHPBB 3.1.10

My configuration is as follows
https://pastebin.com/vvX86guQ

Console:
https://pastebin.com/efqs0mdR

How can I make it work?
For your attention, thank you very much.

**Comment by ljacqu** [comment]
Hi @drAkeTool, thanks for the error report. Should be fixed with build n. 1862 or higher, http://ci.xephi.fr/job/AuthMeReloaded/ It marks the builds as failed at the moment but that's because of an unrelated issue; you can still download the JAR and I promise it's fine. 

Would be thankful for some feedback whether or not we can close this. :)

**Comment by sgdc3** [comment]
@drAkeTool any news? ;)

**Comment by sgdc3** [comment]
@drAkeTool Please open the issue again if the issue persists,
