### ISSUE TITLE
Question, not issue!

### ISSUE THREAD

**Issue by S3nS3IW00** [AuthMe/AuthMeReloaded#1434]
I only have question. Can I get password with method of specified player across API? I need this for players can't send their password to everyone. Thanks for the answer!

**Comment by ljacqu** [comment]
You can use the `checkPassword` method to check if a given password is correct for the player, or you can use `changePassword` to change a player's password. Reading a player's password is currently not supported. That would relate to #1373

**Comment by S3nS3IW00** [comment]
When be supported? I can't solve this with checkPassword(String, String), because it is a boolean function, and contains() is String, the equals() is Object :/

**Comment by ljacqu** [comment]
What exactly are you trying to do?

**Comment by ljacqu** [comment]
If my password is "potato1", and I write in chat "my pass is potato1" you want it to become "my pass is ***" or something?

**Comment by S3nS3IW00** [comment]
I try to do to the players can't send their password to the public chat. If the player send "my password is asd" message the server is cancel it, and send an example message.

**Comment by ljacqu** [comment]
We store all passwords hashed, as is standard practice, so there's no chance to get the cleartext of a user's password.

**Comment by S3nS3IW00** [comment]
This is the problem. In the next update please add this function in the plugin, because is a useable function.

**Comment by ljacqu** [comment]
No.

Once passwords are hashed, there's no way to get back what the text was. And we're certainly not removing the hashing.

**Comment by S3nS3IW00** [comment]
I can detect the password in hash?

**Comment by ljacqu** [comment]
see e.g. SHA-1 https://en.wikipedia.org/wiki/SHA-1

In a nutshell:

Password comes in -> "pass" -> hash algorithm is applied to it -> it becomes something like "9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684" with no function to compute the original text. This 9d4e1e23bd5b727046a9e3b4b7db57bd8d6ee684 text is then stored in the database.

This is enough for us because next time the user wants to log in, he sends "pass" -> again we apply the hash -> we can then check whether the hash is equal to the one we saved. (If e.g. he sends "test" instead, the hash becomes something like "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" -> this is obviously not the same as "9d4e1e23..." so we can say that the login has failed)

The reason for doing this is that should the data from the database ever become breached, the passwords are at least not sitting there waiting to be used.

**Comment by S3nS3IW00** [comment]
Oh I understand. Thanks for explanation! Have a good develop :D
