### ISSUE TITLE
Reminder of Bungee config if Bungee is turned on in spigot.yml

### ISSUE THREAD

**Issue by ljacqu** [AuthMe/AuthMeReloaded#1483]
From @sgdc3:

> we should print a [warning] when bungeecord is enabled in the spigot config to [remind] that the hooks.bungeecord option exists

**Comment by sgdc3** [comment]
@ljacqu does it look good to you?

**Comment by ljacqu** [comment]
Looks great; you chose the best place to implement the check. Thanks for doing it.

**Comment by ant-7802** [comment]
make a force enable please
[AuthMe] Note: Hooks.bungeecord is set to true but your server appears to be running in non-bungeecord mode (see your spigot.yml). In order to prevent untrusted payload attack, BungeeCord hook will be automatically disabled!
I am still getting that even though I have bungeecord enabled
