### ISSUE TITLE
Register/login

### ISSUE THREAD

**Issue by Gaspa123** [AuthMe/AuthMeReloaded#1490]
Hi,
I've a small problem with message, which suppose to appear when i join to server.
For example "please login with command /login <password>"
I've Authme 5.4.0 to 1.8MC

**Comment by sgdc3** [comment]
Please provide more informations, what's the problem, what did you expect to happen?

**Comment by Gmodero** [comment]
Same problem here. The login message doesn't display when a player enters the game (I mean "Please type /login password) to remind players that they have to login.
Authme 5.2 for Minecraft 1.7.10 (kCauldron server)

**Comment by Gaspa123** [comment]
Yes exactly, I have the same problem and I have no idea where is my mistake

**Comment by Gmodero** [comment]
Ok I fixed it, but I did it just reinstalling AuthMe on my server. It works again for now, but I don't know if in the future it will fail again. It's anoying, because ok, some users don't have problems because they've played a lot of servers, but another players forget that they have to log in and the are like "admin please wtf i cant move". 

You can put the message on Essentials motd, but it's not the same, it just displays once.

**Comment by Gaspa123** [comment]
I did reintalling but still the same problem :/

**Comment by sgdc3** [comment]
@Gaspa123 could you try the latest dev build? https://ci.codemc.org/job/AuthMeReloaded/
