### ISSUE TITLE
Fastlogin / AuthMe - autounregister if premium and if user not logged x-days and if premium name y-days

### ISSUE THREAD

**Issue by minecraft7net** [AuthMe/AuthMeReloaded#1496]
Hi,

i have a request for AuthMeReloaded addon and for FastLogin addon

**Addon description:**

solutions for server using AuthMeReloaded and after 3-4 years start using FastLogin

addon that will:
1. check if player is premium
2. check if the same username exists in AuthMeReloaded database
3. check if the player in AuthMeReloaded database is inactive for configured time 600+ days
4. check if premium user has this Name/Nickname in mojang history more than configured time 300+ days

5A. and option for manual unregister by oplayer premium /force-login
5B. auto unregister

or maybe someone had idea how to code it in AuthMe?

commands.yml (?)
onJoin: {} ?
onRegister: {} ?

**Comment by sgdc3** [comment]
You should move this issue to the fast login issue page, talk with @games647

**Comment by minecraft7net** [comment]
i was ask but his project is smaller and he is a bit busy i think, i make also on fastlogin request. https://github.com/games647/FastLogin/issues/192

**Comment by ljacqu** [comment]
Since FastLogin integrates AuthMe (among other systems) it would make sense for this to be a feature in FastLogin. AuthMe doesn't have the ability to check whether a username is premium and that is in fact something that is beyond our scope. The only thing that is required from AuthMe are points 2 and 3, which we expose through our API. So nothing blocks this being implemented outside of AuthMe.

**Comment by games647** [comment]
What about an Purge event, that AuthMe can notify other plugins to delete the player data?

**Comment by ljacqu** [comment]
A purge event would definitely be a good idea! This is planned within #616
