### ISSUE TITLE
Strange bug with useAutoPurge

### ISSUE THREAD

**Issue by Twonox** [AuthMe/AuthMeReloaded#1500]
Hi,

A friend has a problem with authme, but I don't know why it happen only on his server and not in mine when I test it.
So, the problem is the following. He put the latest build of Authme in the plugin folder for the first time, this mean there is not yet authme's config folder. It boot the server without problem, authme works. But come the moment where he restart the server, and at this moment authme won't load and server won't start, with this error log:
https://hastebin.com/tatudaloji.vbs
So, I checked these lines, and I noticed that the line of autoPurge parameter was moved to left and was changed to true (default is false). When I set it to false, it's automaticcaly changed to true after a reboot (which is thus fail). **Befor:** https://image.noelshack.com/fichiers/2018/06/7/1518306240-2018-02-11-004314.png, **after:** https://image.noelshack.com/fichiers/2018/06/7/1518306242-2018-02-11-004331.png

Servers version: Spigot 1.8.8 latest build
Without Bungeecord

**Comment by sgdc3** [comment]
@ljacqu maybe a configme issue?

**Comment by ljacqu** [comment]
A ParserException happens when the file to be loaded isn't valid YAML. I think your friend changed the config.yml to the following:
```yml
    # If enabled, AuthMe automatically purges old, unused accounts
    useAutoPurge: false
    # Number of days after which an account should be purged
      daysBeforeRemovePlayer: 60
```

(notice the extra lines before `daysBeforeRemovePlayer`). This change produces the error you've provided, and rightfully so: by adding more spaces it's as if `daysBeforeRemovePlayer` were a subsection of `useAutoPurge`, but that property is already being assigned a value immediately.

If you can post us step by step instructions on how leaving `useAutoPurge: false` can suddenly become `true` we'll need to investigate this, but from my point of view it looks like your friend wanted to change it to `true` and then accidentally made the YAML invalid.

**Comment by Twonox** [comment]
He doesn't changed anything of authme's config. I have tested using his FTP and console. After a first load of authme (which is okay), these things happens immediatly after the reboot of the server, every time.
I can record the steps if you want.

**Comment by ljacqu** [comment]
Sure, that would be helpful, but seeing as you and I don't observe this elsewhere (right?) all I can think is that your friend's FTP server or whatever is doing something strange.

**Comment by Twonox** [comment]
https://www.youtube.com/watch?v=BzF42WrPPWk

**Comment by ljacqu** [comment]
Thank you for the video. Right now I have no explanation, so tomorrow I'll offer a JAR with more debug output. I don't understand why it would break only on that line. In fact it shouldn't even rewrite to the config.yml. I wonder if this happens on shutdown rather than startup.

**Comment by Twonox** [comment]
Good news, I've contacted directly the hosting company, and they said that the problem came from them.
Now it's fixed.

**Comment by ljacqu** [comment]
Hi @Twonox , thanks a lot for the update and for your initiative on getting the matter resolved. I'm glad that it's working on your end now :)
