### ISSUE TITLE
Fix Optional logging in bungee receiver / sender

### ISSUE THREAD

**Issue by sgdc3** [AuthMe/AuthMeReloaded#1625]

**Comment by samyratchet** [comment]
Hello,

I have the same issue, i used the newest dev build authme reloaded and authmebridge. When using the dev builds and try to connect to the lobby it says authenticate. So i cant even get in the server to login.

When using the last released authmebridge plugin downloaded from spigot, i get on the server i can login but i cant switch to another server or use commands. If i try to switch it says authenticate.

Yes i have changed in the authmebridge config the authme server is Lobby also in the authmereloaded config it was already hooked with bungeecord.

Because of this buggs, i am using back the older versions of authmereloaded and authmebridge and they work fine.

The reason i wanted to update to the last version is because the known buggs where fixed there.

Thanks dev for updating autme ;)
