### ISSUE TITLE
/email show, doesn't work without logging in first

### ISSUE THREAD

**Issue by Guest1131** [AuthMe/AuthMeReloaded#1682]
Hi, there,

I noticed that there is a problem...I can not do /email show, to see the email, outside the login.

If I forget my password, and I have to do /email recovery to return, and I don't remember the email address anymore, how do I see it without login?

**Comment by ljacqu** [comment]
This is by intention because we wouldn't want to allow everyone to look up the email address that a user has registered with. I would vote not to change this due to privacy concerns — as on other sites, essentially if you forgot your email address you're in trouble :) And that's hopefully when a friendly staff member or a post on your server's forum comes into play.
