### ISSUE TITLE
Login timeout

### ISSUE THREAD

**Issue by iiLearner** [AuthMe/AuthMeReloaded#1806]
#### Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!

Hello, I'm using latest version of authme reloaded (AuthMe-5.6.0-SNAPSHOT.jar), and I'm having this issue where when players try to login, they timeout after several seconds.

1. Player connects (shows UUID of player in console)
2. MC says loading terrain.. stays there for about 30 seconds and gets kicked with message "remote host has closed the connection (noy exact). "Player" has timedout appears in console.

Timings report: https://i.imgur.com/C6ZEa7Q.png

**Comment by iiLearner** [comment]
It does not happen with all players though.

**Comment by sgdc3** [comment]
Which server version are you running? Please provide more info.

**Comment by iiLearner** [comment]
Running spigot 1.13.2

**Comment by iiLearner** [comment]
Bump.

**Comment by ljacqu** [comment]
Issues like these are hard for us to address because there's not much information for us to go on. A slow server could be due to many things—is it completely at its limit anyway to the point that there's no memory to run anything, is it something that happens because the database is set up strangely? 

Reports like "after upgrading from version 77 to 79 everything is much slower" is already better since it's quite plausible that we've broken something in this hypothetical situation, or something like "since having 1000 registered users everything is slow" gives us a good idea of what's going on.

Given that we haven't heard more reports in this direction I'm afraid I'm inclined to close this. We can gladly revisit this issue but we'll need some effort on your side to provide us with any and all details you can think of, starting with your config.yml, the database engine you're using and how many registered users there are, some server specs, maybe some timings (or at least some tests you do manually) with and without AuthMe.
