### ISSUE TITLE
Email error

### ISSUE THREAD

**Issue by MrWay** [AuthMe/AuthMeReloaded#1815]
### What behaviour is observed:
I am unable to connect authme to our smtp server and i don't know why.

### What behaviour is expected:
Connection to our smtp via ssl.

### Plugin list:
AuthMe, WorldEdit, FastLogin

### Environment description
Bungeecord network, mysql

### AuthMe build number:
v5.6.0-beta1

### Error Log:
https://pastebin.com/796iANS9

### Configuration:
https://pastebin.com/AAQNS2GN

**Comment by ljacqu** [comment]
> Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

It can't connect through SSL because of an invalid certificate. This can be your mail server that has some misconfiguration but it can also be the machine running the server that doesn't have the needed certificates. Are you running the server locally? For instance, I get such issues on my PC but never on a real server.

**Comment by ljacqu** [comment]
This is the same error as in #1772 (just posting a comment so they get linked)

**Comment by ljacqu** [comment]
Closing as a duplicate since we haven't been given more details and it is the same as the aforementioned issue. So let's use #1772 to track this problem.
