### ISSUE TITLE
Authme security flaw

### ISSUE THREAD

**Issue by SuperMatyCZE** [AuthMe/AuthMeReloaded#1847]
Hey! Iam running a small server with my friends. We are having issues with people just logging into admin accounts. We are not running our server in online mode, beaceuse a lot of our friends don't have Minecraft purchased. We are running Paper 1.14.2. 
Basicaly, someone just connect with and user name on and admin with a warez launcher and just loggs in with the password. Just like that. All of our admin accounts have password of atleast 10 characters, numbers, specials symblots and big characters. We tryed updating to the latest build, reinstalling the plugin, making new password to our ftp database, banning the ip that we found connected to the admin accounts but nothing helped.
Do you have any ideas how we coud fix this? Thanks

**Comment by ljacqu** [comment]
Could you share the authme.log please? You can also send it to my github username at hotmail.com if you don't want to publicly share it

**Comment by SuperMatyCZE** [comment]
Can't send it to your email. Your mailbox in unavailable.

**Comment by SuperMatyCZE** [comment]
Ok, I sent it

**Comment by ljacqu** [comment]
Thanks, which users am I looking for? I see nothing out of the ordinary... Can you maybe send me the server log as well so we see when players join vs. when they log in? 
As mentioned, right now nothing catches my eye and it would seem that they'd have to have known the password beforehand somehow.

**Comment by SuperMatyCZE** [comment]
User Alfasamec

And yea, that's the thing. They just log on. Just like that. No wrong attempts, nothing.

**Comment by ljacqu** [comment]
They must know your password from elsewhere. I don't really see any other way that this is being done since there are no failed password items prior to that (well, there is one, but not 50)...

I don't see the join times (to compare with the login times); if those are just a second apart _then_ we could argue there's something they're exploiting, but right now it really just seems like they are able to log in because they know that user's password.

**Comment by ljacqu** [comment]
It feels wrong to close this, since _if_ there is an issue on our side it would have top priority.

We discussed this internally with a focus on Bungeecord and didn't find anything wrong, assuming AuthMe is used with our official bungee extension, AuthMeBungee. On the other hand, using it with AuthMeBridge would be very bad news as it's severely outdated, to the point that newer versions of AuthMe will actually shut down the server if they detect it.

If you still encounter this behavior after changing your password we are _very_ interested in hearing about it and we could look into logging the hell out of certain portions of the code to hopefully determine what is going on. So please let us know if this happens again and we'll reopen this and give it the highest priority.
