### ISSUE TITLE
PBKDF2 website integration hash problem

### ISSUE THREAD

**Issue by PlayerNguyen** [AuthMe/AuthMeReloaded#1885]
### What behaviour is observed:
I've seen in https://github.com/AuthMe/AuthMeReloaded/blob/master/samples/website_integration/Pbkdf2.php that the function compute_hash(). It missed first '$' symbol

Example:
Im trying to hash '123' with pbkdf2 algorithm. It's must $pbkdf2_sha256$10000$a738f3a935eb309d$646a0eb24103cc6d39466101745746087264384c2adbad9fe0cf277ccf6cac19 
instead of pbkdf2_sha256$10000$a738f3a935eb309d$646a0eb24103cc6d39466101745746087264384c2adbad9fe0cf277ccf6cac19

### What behaviour is expected:
What did you expect?

### Steps/models to reproduce:
The actions that cause the issue

### Plugin list:
This can be found by running `/pl`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...

### AuthMe build number:
This can be found by running `/authme version`

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)

**Comment by ljacqu** [comment]
Strange because when I look at the Java implementation ([https://github.com/AuthMe/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/security/crypts/Pbkdf2.java]) and the test class ([https://github.com/AuthMe/AuthMeReloaded/blob/master/src/test/java/fr/xephi/authme/security/crypts/Pbkdf2Test.java]) it's quite apparent that there is no starting `$`. Is this a false issue or is there something else going on here?
