### ISSUE TITLE
[Feature Request] infinite session timeout

### ISSUE THREAD

**Issue by Phr3d13** [AuthMe/AuthMeReloaded#1901]
With old versions of the plugin, I could set the session timeout to 0 and the session would never expire. With the current version, it's behaving more like an instantly expiring session.

**Comment by ljacqu** [comment]
We removed it due to security reasons, what you can do instead is figure out the number of seconds for a reasonable interval (even for a week, if you deem that secure enough) and for most players it should hopefully act as infinite :) Maybe seems like a cheap answer to your problem but hopefully that's a viable compromise for you.

**Comment by ljacqu** [comment]
Excellent :)
