### ISSUE TITLE
not changing the password

### ISSUE THREAD

**Issue by SuperJogosDBZ** [AuthMe/AuthMeReloaded#1970]
### What behaviour is observed:
What happened?
the /cp command is not changing the password, I set the plugin to ask for an email confirmation when changing the password, the email arrives, it gives the confirmation command, and the user sees in the chat that the password has been changed, but when he relog the password is still the old one.

### What behaviour is expected:
What did you expect?
be able to change the password correctly

### Steps/models to reproduce:
The actions that cause the issue
change Password

### Plugin list:
This can be found by running `/pl`

### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Lobby/Bungeecord Mysql

### AuthMe build number:
This can be found by running `/authme version`
AuthMeReloaded v5.6.0-beta1 (build: 2226)

### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)

### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://pastebin.com/JdKzyagj

**Comment by ljacqu** [comment]
Have you been able to reproduce this? Does it work if you change the password with `/authme changepassword`?

**Comment by SuperJogosDBZ** [comment]
No, when the password is changed directly, it does not happen. I think the problem is happening because of the confirmation that he asks in the email.

**Comment by ljacqu** [comment]
I just tried it and I can play through it just fine (minus being kicked out a few times because your timeout is quite low :P). I think the crucial detail, re-reading your issue description again, is that one has to use the command `/email setpassword` and not `/cp` after the code is used. There's a message that says so once you successfully enter the code, but maybe due to the low timeout you've configured people miss it.
