### ISSUE TITLE
Use of commands without being logged

### ISSUE THREAD

**Issue by esponjosin** [AuthMe/AuthMeReloaded#1997]
Issue: Users can log in with an account and use commands without being logged in or registered

Action: Join server > Run a Command 

Plugins: AuthMe, BlockParticles, BuycraftX, Citizens, CitizensCMD, ClearLag, ConsoleSpamFix, CrazyAuctions, CrazyCrates, DeluxeMenus, DerpyTogglePvP, DisableAI*, DiscordSRV, Drupi*, EntityTrackerFixer, EpicGuard, EpicRename, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, ExploitFixer, FastAsyncWorldEdit, Holograms*, IllegalStack, ItemParticles, Jobs, Limbo*, LimitPillagers, MarriageMaster, MineResetLite, MobFarmManager, Multiverse-Core, MVdWPlaceholderAPI*, newtLib, newtSlime, OreAnnouncer, PermissionsEx*, PL-Hide, PlaceholderAPI, PlugMan, ProtectionStones, ShopGUIPlus, SinglePlayerSleep, SkinsRestorer, TAB, TDG, UltimateTimber, Vault, VillagerOptimiser, VoidGenerator, VoidTP*, WorldBorder, WorldEdit, WorldGuard

Backend: SQlite

Version: AuthMeReloaded v5.6.0-SNAPSHOT (build: 2371)

Config: https://pastebin.com/Ev23990n

**Comment by ljacqu** [comment]
Server version?

Also, any kind of command from other plugins, or just AuthMe commands, or just commands from some other plugin?

**Comment by esponjosin** [comment]
> Server version?
> 
> Also, any kind of command from other plugins, or just AuthMe commands, or just commands from some other plugin?

Version: 1.15.2

They can use any command of another complement, whether or not authme

**Comment by ljacqu** [comment]
This looks to me like it's some other plugin interfering with AuthMe. I think we can rule out permissions since AuthMe doesn't have any permissions in the area of allowing unauthenticated commands...
Unfortunately, this means we'd have to ask you to try to narrow down the cause by gradually reducing the number of plugins in a test environment, or the other way around (add AuthMe, see if the bug is there, then gradually add more of the plugins that you use). This is my assumption based on your large plugin list and the fact that no one else has reported this bug.
