### ISSUE TITLE
Essentiasl & AuthMe "/l command"

### ISSUE THREAD

**Issue by Laielix** [AuthMe/AuthMeReloaded#2032]
Every time I try to use /l to log in, it tells me that I don't have permissions, this is because essentials uses the /l command to display the list of online players. How can I fix this problem?

**Comment by scorninpc** [comment]
This conflict with /l from others plugins too. I've remove /l from command list, but still conflicting 

```
restrictions:
        # Can not authenticated players chat?
        # Keep in mind that this feature also blocks all commands not
        # listed in the list below.
        allowChat: false
        # Hide the chat log from players who are not authenticated?
        hideChat: false
        # Allowed commands for unauthenticated players
        allowCommands: 
        - /login
        - /register
        # - /l
        # - /reg
        # - /email
        # - /captcha
        # - /2fa
        # - /totp```

**Comment by scorninpc** [comment]
Conflict with anothers plugins too. Maybe we can disable this aliases?

**Comment by syde-sb** [comment]
/l is not Essentials command. If you are using MyCommands, then delete list alias from examples.yml.

**Comment by scorninpc** [comment]
This / l conflict with localchat. / l are use all the time to talk local, instead / login are used just one time when login only. I'v done my compile removing that, but have a config for that will be great

**Comment by ljacqu** [comment]
I think you can resolve alias conflicts with Spigot's commands.yml, https://bukkit.gamepedia.com/Commands.yml

IMHO on our side it's not easy to make it configurable because the plugin system requires us to define aliases in the plugin.yml that we ship with the JAR, so we don't have a way of dynamically adding or removing entries in there apart from offering multiple JAR files (which doesn't make sense for such a distinction).
