### ISSUE TITLE
AuthMe thinks that me and other players are in the same IP but we aren't

### ISSUE THREAD

**Issue by Hissam1048v** [AuthMe/AuthMeReloaded#2203]
### What behaviour is observed:
What happened?
It shows that I own 2 accounts, 
Account 1 (me), Account 2 (some other player which isn't my account)
### What behaviour is expected:
What did you expect?
Just Account 1 was supposed to be there.
And we are not in the same IP so AuthMe was supposed to consider us as seperated.
### Steps/models to reproduce:
The actions that cause the issue
I don't really know.
### Plugin list:
This can be found by running `/pl`
AntiCheatReloaded, AuthMe, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, ProtocolLib, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit.

Also, I am using the AuthMe bungee.
### Environment description
Standalone server/Bungeecord network, SQLite/MySql, ...
Bungeecord network.
### AuthMe build number:
This can be found by running `/authme version`
Version: AuthMeReloaded v5.6.0-beta1 (build: 2226)
### Error Log:
Pastebin/Hastebin/Gist link of the error log or stacktrace (if any)
No error
### Configuration:
Pastebin/Hastebin/Gist link of your config.yml file (remember to delete any sensitive data)
https://paste.gg/p/anonymous/f5b62303e7b043628f05415b7eab0b9d

**Comment by dusekdan** [comment]
Hi, can you provide more context on how you ensure that you are not on the same IP?

The way AuthMe works is that it marks down the IP address from which an account was first registered. Since that moment, it will always report that specific username for other players joining from that IP. 

As IPv4 is a scarce commodity these days, it is very probable that you share yours with someone else. Your Internet Service Provider probably uses the same "public" IPv4 for multiple clients, or even for the subnet of clients (to use their assigned public IPs efficiently). In practice, this means that the whole building or even a small street can share the same IP address - the one that AuthMe sees, and that may be why you see that Account 2.

**Comment by MrIvanPlays** [comment]
Unable to reproduce.

**Comment by DriftyDev** [comment]
using bungeecord?

**Comment by CroaBeast** [comment]
I have the exact same problem, and I'm using it in a spigot-based server (without bungeecord)

**Comment by sgdc3** [comment]
@CroaBeast are you using services like TcpShield or another ddos protection layer?
