### ISSUE TITLE
Translation Mistake

### ISSUE THREAD

**Issue by XiaoXiaoYuMC** [AuthMe/AuthMeReloaded#2795]
### What feature do you want to see added?

Please change the region name of the zh_cn version translation to **Chinese Mainland** instead of **China**.

### Are there any alternatives?

Please change the region name of the zh_cn version translation to **Chinese Mainland** instead of **China**.

**Comment by ljacqu** [comment]
I had a bit of look around—this issue seems politically motivated. Other major platforms refer to zh-CN as "Chinese (China)", so I think we're happy with that too.

https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/available-language-packs-for-windows?view=windows-11
https://developers.facebook.com/docs/messenger-platform/messenger-profile/supported-locales/
https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html
