### ISSUE TITLE
Custom crypt class in the plugin folder

### ISSUE THREAD

**Issue by sgdc3** [AuthMe/AuthMeReloaded#693]
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/?comment=6616
http://dev.bukkit.org/bukkit-plugins/authme-reloaded/?comment=6618

**Comment by ljacqu** [comment]
One possiblity would be a config setting with the full class name, e.g.:

```yml
customCrypt: 'com.example.crypts.CustomCrypt'
```
Then the class just needs to be present during class loading.

From a security standpoint I wouldn't recommend using custom hashes, though. The one mentioned in the comment ought to be replaced with Bcrypt or so. Custom hash is a bad idea, unless it's for hooking into some other system.

**Comment by ljacqu** [comment]
Hmm, thinking about this and @sgdc3's comment he linked. Some API call would ensure the class is already loaded. Not too familiar how classes are loaded... but essentially it depends how that custom class can be added. It's not as simple as dropping the java file into the JAR's crypt folder :P

**Comment by ljacqu** [comment]
Never heard of this request again and a homebrew hash method is, as we know, a bad idea. Our BCRYPT hash algorithm works well with PHP's [password_hash()](https://www.php.net/manual/en/function.password-hash.php) so that should be ~sufficient~ preferred. 

Otherwise -> listen to & modify PasswordEncryptionEvent
