### ISSUE TITLE
Store registration IP and date

### ISSUE THREAD

**Issue by Twonox** [AuthMe/AuthMeReloaded#792]
improve:   _/authme getip <pseudo>_  -  Display the first IP of the player (when registered) and old IPs.
add:  _/authme check <pseudo>_  -  Show the date of registering and show if player is registered.
add:  _AntiVPN_  -  The contry blacklisting isn't 100% efficiency, also why not add an AntiVPN like https://www.spigotmc.org/resources/protect-your-server-with-the-new-anti-vpn-plugin-1-7-and-1-8.18726/ This plugins is very efficiency but isn't up to date, if you add this to Authme with improvement, it can be better.

**Comment by sgdc3** [comment]
Maybe on future:
1) we only store the last ip in our database
2) we don't store the registration date
WontFix:
3) we are not an antibot plugin xD

**Comment by Twonox** [comment]
1) You can't store it?
2) You can't store it?
3) LOL, then what is that? xD
```
Features:​
Built-in AntiBot System!
```

**Comment by ljacqu** [comment]
@Twonox for 1 and 2: we could store it, of course. But this complicates the application by having two more fields. It's not just two more columns in the database, but it's two additional properties to make them configurable, additional error handling to make sure the columns are there and to create them if not, additional logic to retrieve these column values from our various data sources.
And that's fine, it's nothing too complex, but this will all be additional code that we will then have to maintain in our application as the application will change. It essentially boils down to this: is the additional code worth the benefit it brings? If more people would like this, I'm up for it. Otherwise, no.

3: Our antibot system is fired when too many unregistered accounts join in a configurable interval, kind of like a "bot invasion". Then it kicks in and prevents more from logging on. This has nothing to do with detecting proxies or VPN connections.

**Comment by ljacqu** [comment]
Granted, if someone else would want to contribute to AuthMe, 1 and 2 would make for a great introductory story to get to know the project.

**Comment by sgdc3** [comment]
Yeah, you're right ;)

**Comment by ljacqu** [comment]
This creates changes in the DB and in the semantics for purging, so although I'm working on this I'm moving this to 5.4 because I don't want to rush it.

**Comment by sgdc3** [comment]
@ljacqu Could we close this?

**Comment by ljacqu** [comment]
Yes, this is done—finally
