### ISSUE TITLE
Use data purger when issue unregister cmd.

### ISSUE THREAD

**Issue by Kixot14** [AuthMe/AuthMeReloaded#923]
In my server allowed only 1 account per player. I banned players, if they try to walk around this limit and register another account for claim new region or dupe something...

Authme have limit registration per IP feature, and it's cool because not all players know how to use proxy for registration twinks. But if i want to add /unregister command for players, this IP limit becomes not actual because player can for example reg 1 acc, claim region, unreg, reg another, claim.....

So solution is perform smart purger in connection with /unregister.
But first you need to add many different purgers which can touch data from all known plugins :)

**Comment by ljacqu** [comment]
Naïve implementation would be to add an option that runs the purge process on /unregister. Might make sense to issue a warning before the player really unregisters (because, like, what if someone just quickly wants to change password via unregister? It's a bad way to change one's password, but I remember doing it too when I wasn't familiar with AuthMe's commands). 

I think a better solution might be with the force command options (#411) and the addition of an `/authme purgeplayer xx` command (which might be interesting in general). This gives the user more freedom and doesn't clutter our config with even more options.

Adding more purgers / allowing others to hook into our purge process should be discussed in another issue IMHO as to keep this one clear.

**Comment by ljacqu** [comment]
- Created `/authme purgeplayer` command
- Added `onUnregister` to commands.yml

I still don't think this is the ultimate solution, so if you have an idea to improve this let's create a follow-up issue :)

**Comment by sgdc3** [comment]
@Kixot14 does it work?
