### ISSUE TITLE
Allow password changes without login (easier Bungeecord handling)

### ISSUE THREAD

**Issue by Dimatert9** [AuthMe/AuthMeReloaded#973]
Hello. When active bungee-mode and set sendTo players can't change password, because after login they will send to other server. How about make /login yourpassword newPw repeatNewPw
Or /changepassword yourPassword newPw repeatNewPw when you aren't login.

**Comment by Twonox** [comment]
```
# Commands allowed when a player is not authenticated
  allowCommands:
  - /changepassword
```

**Comment by sgdc3** [comment]
Whoops misread this issue, you can change your password before /login

**Comment by sgdc3** [comment]
># Commands allowed when a player is not authenticated
  allowCommands:
  - /changepassword

Useless, authme alredy allows user to use such commands.

**Comment by sgdc3** [comment]
@Dimatert9 if you have issue with /changepassword before login please comment there. :)

**Comment by ljacqu** [comment]
Just one thing, `/changepassword` isn't allowed to be used by unlogged players by default, Dimatert9's config cleverly fixes that. It's important to note that /changepassword isn't secured against any bruteforce attacks.

**Comment by sgdc3** [comment]
@ljacqu Really? We should apply the kick on wrong password also to the changepassword command i think.

**Comment by ljacqu** [comment]
I checked, and the change password command checks if player is logged in or not. So even with the config it will just send a "you are not logged in" error message.

Currently, it probably makes sense to use some form of threshold for failed password changed attempts. Probably it's OK to combine with our current solution (TempbanManager). 

Allowing unlogged users to change their password seems a little odd to me, but maybe that's only because we don't see it usually because it doesn't make sense.
