### ISSUE TITLE
PlayQuitEvent cause lag ?

### ISSUE THREAD

**Issue by Twonox** [AuthMe/AuthMeReloaded#991]
http://image.noelshack.com/fichiers/2016/43/1477321361-2016-10-24-170211.png

**Comment by Twonox** [comment]
http://image.noelshack.com/fichiers/2016/43/1477322237-2016-10-24-171706.png

**Comment by sgdc3** [comment]
please post your entire timings and your config

**Comment by Twonox** [comment]
https://timings.spigotmc.org/?url=piseqebeha
http://hastebin.com/kifipanowi.bash

**Comment by sgdc3** [comment]
Please try with useAsyncTasks set to true

**Comment by Twonox** [comment]
It's better in timings with Async mode. I think it doesn't cause lag.
http://image.noelshack.com/fichiers/2016/43/1477404203-2016-10-25-160303.png

But in Async mode there is little bugs (multiple account's message is sent x2 and if I register a player in server B, he's registered a fex seconds later in server A, because I use the same db for my servers

**Comment by Eufranio** [comment]
Hmmm, then https://github.com/games647/FastLogin/issues/91 is related to Async?

**Comment by sgdc3** [comment]
@ljacqu our listeners and processes are still too resource expensive...

**Comment by DNx5** [comment]
the percentage total and the count is low, how long is the timings taken? i see no problem with that timings report.

**Comment by Twonox** [comment]
https://timings.spigotmc.org/?url=gihohayuqi
And now what do you think ?

**Comment by ljacqu** [comment]
This is troublesome. I see some potential for performance improvement (like caching the first spawn location) but those are all things that shouldn't slow things down massively. Since onJoin and onQuit are mostly the bad guys I guess it's safe to assume it's the interaction with the DB. If this is in async it's quite surprising that onQuit is so slow...

We fire three queries to the DB on player quit, this could be optimized to one. Maybe I can set up Perf4j on AuthMe sometime and we can log the execution time for individual sections.

**Comment by DNx5** [comment]
that timings still doesnt show AuthMe is causing the lag.
@ljacqu that would be a minor improvement, I think we should focus on bugs fixing for now.

**Comment by sgdc3** [comment]
@Twonox Could you provide new timings please? ;)

**Comment by Twonox** [comment]
I can't send new timings to comparing because there is no longer have so much players in my server :/
